[profile.default]
src           = "src"
out           = "out"
libs          = ["lib"]
test          = "test"
script        = "script"
solc          = "0.8.24"
test          = "test"
no_match_path = "test/legacy/**"

# Fuzz config
[fuzz]
runs = 500

# Coverage
[profile.coverage]
via_ir = true

# Invariant
[invariant]
runs   = 256
depth  = 15

# Formatter — excluir dependencias
#[fmt]
#exclude = ["lib/**"]