[profile.default]
src           = "src"
out           = "out"
libs          = ["lib"]
test          = "test"
script        = "script"
solc          = "0.8.24"
no_match_path = "test/legacy/**"

# Fuzz config
[fuzz]
runs = 500

# Invariant
[invariant]
runs   = 256
depth  = 15

[profile.default.coverage]
exclude = [
    "script/**",
    "test/**",
    "src/legacy/**"
]